## Feature Selection using Different Ranking Techniques

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder #string labels to int
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.decomposition import PCA as PCA
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, mutual_info_classif

In [14]:
import platform
platform.python_version()


'2.7.15'

### Load the features
random dataframe for now

In [2]:
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))

Put values and labels of the dataframe into matrices

In [3]:
X = df.values
y = np.random.randint(2, size=100)

### Apply LDA

In [4]:
lda = LDA()
lda.fit(X, y)
scores_lda = lda.scalings_

In [5]:
scores_lda

array([[-0.02099493],
       [-0.01258209],
       [-0.01181706],
       [-0.01821207]])

### Apply PCA
linearly transforms initial features into a new space therefore scores does not directly correspond to the initial 4 features we have but they correspont to the vectors that combine the 4 features

In [6]:
pca = PCA()
pca.fit(X, y)
scores_pca = pca.explained_variance_ratio_ #percentage of explained variance per component

In [7]:
scores_pca

array([0.30495829, 0.25209725, 0.22596011, 0.21698435])

### Apply Feature Selection with chi-squared
X must contoin non-negative values

In [8]:
chi = SelectKBest(chi2, k=X.shape[1]).fit(X, y)
scores_chi = chi.scores_

In [9]:
scores_chi

array([24.03763936, 14.2910722 , 12.86464263, 24.17422831])

### Feature selection with Mutual Info
relies on nonparametric methods based on entropy estimation from k-nearest neighbors distances

In [10]:
mutin = SelectKBest(mutual_info_classif, k=X.shape[1]).fit(X, y)
scores_mutin = mutin.scores_

In [11]:
scores_mutin

array([0.09113307, 0.02526958, 0.        , 0.02138309])